import Head from "next/head";
// import styles from '../styles/Home.module.css'
import styles from "../styles/secondPage.module.scss";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";

import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer";
import { items } from "./components/ArticlePage/item";
import Partenariat from "./components/partenariat/partenariat";
import ImageArticle from "./components/imageArticle/imageArticle";
import Carousel from "react-bootstrap/Carousel";

const imgg1 = new URL("../../public/assets/IMG_blog1.jpg", import.meta.url);
export default function SecondPageArticle(id) {
  const router = useRouter();
  var id1 = router.query.id;
  const [article, setArticle] = useState();
  var myObject = items.find((item) => item.id1 === id1);
  console.log(myObject);

  useEffect(() => {
    //use id to get article Data from back
    setArticle(items[id1 - 1]);
  }, [id1]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <div className={styles.flex_container_page}>
        {/* <h2 className={styles.titre}>{myObject.title}</h2>
        <div className={styles.article}>{myObject.content}</div>
        <img className={styles.image1} src={myObject.image} /> */}

        {/*  <h1>{items[parseInt(id1)].id}</h1> */}
        {article ? (
          <Carousel>
            <Carousel.Item>
              <img
                className="d-block w-100"
                src={article.image}
                alt="First slide"
              />
              <Carousel.Caption>
                <h3>{article.title}</h3>
                <p>{article.content}</p>
              </Carousel.Caption>
            </Carousel.Item>
            <Carousel.Item>
              <img
                className="d-block w-100 cc"
                src={article.image1}
                alt="First slide"
                width="400"
              />
              <Carousel.Caption>
                <h3>{article.title}</h3>
                <p>{article.content}</p>
              </Carousel.Caption>
            </Carousel.Item>
            <Carousel.Item>
              <img
                className="d-block w-100"
                src={article.image2}
                alt="First slide"
              />
              <Carousel.Caption>
                <h3>{article.title}</h3>
                <p>{article.content}</p>
              </Carousel.Caption>
            </Carousel.Item>
          </Carousel>
        ) : null}

        <button
          className={styles.btnR}
          onClick={() => {
            router.back();
          }}
        >
          {" "}
          Retour
        </button>
      </div>
      <Footer />
    </div>
  );
}
